fix: reflection (#20)
This (slightly hackily) works around an issue that the underlying driver seems
to convert Python ints in bound parameters to BIGINT, which makes it difficult
to use them in arguments to functions that only have INT versions, and these
functions are used in SQLAlchemy's reflection system.

When https://github.com/apache/arrow-adbc/pull/2881 is merged/deployed,
hopefully we can remove the work around.

This includes a bump of the minimum SQLAlchemy version on Python 3.13 to fix
the error when traversing:

AttributeError: 'functools._lru_cache_wrapper' object has no attribute
'_annotations'. Did you mean: '__annotations__'?